/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;

import entities.Email;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.LookAndFeel;
import javax.swing.UIManager;
import javax.swing.border.Border;
import utilities.EmailUtils;

/**
 *
 * @author duong
 */
public class JFrame_Java extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form JFrame_Java
     */
    public JFrame_Java() {
        
        try {
            UIManager.setLookAndFeel(new FlatMacLightLaf());
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        initComponents();
        
        setSize(700, 500);
        
        setTitle("Java Swing: Demo Compose an Email | Google Developer Student Clubs - IUH");
        
        setLocationRelativeTo(null);
        
        jLabel2.setPreferredSize(lblSubject.getPreferredSize());
        jLabel3.setPreferredSize(lblSubject.getPreferredSize());
        
        lblNewMessage.setFont(new Font("Arial", Font.BOLD, 14));
        
        btnSend.addActionListener(this);
        btnCancel.addActionListener(this);
        btnLoadDraft.addActionListener(this);
        btnSaveDraft.addActionListener(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        panelNorth = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtFrom = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTo = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        lblSubject = new javax.swing.JLabel();
        txtSubject = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        lblNewMessage = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnSend = new javax.swing.JButton();
        btnSaveDraft = new javax.swing.JButton();
        btnLoadDraft = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaContent = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {0, 23, 0, 23, 0};
        jPanel3Layout.rowHeights = new int[] {0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0};
        panelNorth.setLayout(jPanel3Layout);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setText("From:");
        jPanel6.add(jLabel3);

        txtFrom.setText("core-team-members@iuhgdsc");
        txtFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFromActionPerformed(evt);
            }
        });
        jPanel6.add(txtFrom);

        jPanel5.add(jPanel6);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        panelNorth.add(jPanel5, gridBagConstraints);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("To:");
        jLabel2.setPreferredSize(new java.awt.Dimension(42, 16));
        jPanel1.add(jLabel2);

        txtTo.setText("all-members@iuhgdsc");
        txtTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtToActionPerformed(evt);
            }
        });
        jPanel1.add(txtTo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        panelNorth.add(jPanel1, gridBagConstraints);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        lblSubject.setText("Subject:");
        jPanel7.add(lblSubject);

        txtSubject.setText("[IUH GDSC] Workshop Java Swing: Lời cảm ơn");
        txtSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubjectActionPerformed(evt);
            }
        });
        jPanel7.add(txtSubject);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        panelNorth.add(jPanel7, gridBagConstraints);

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        lblNewMessage.setText("New Message");
        jPanel8.add(lblNewMessage);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth.add(jPanel8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        jPanel2.add(panelNorth, gridBagConstraints);

        jPanel4.setLayout(new java.awt.BorderLayout());

        btnSend.setText("Gửi");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        jPanel3.add(btnSend);

        btnSaveDraft.setText("Lưu bản nháp");
        btnSaveDraft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDraftActionPerformed(evt);
            }
        });
        jPanel3.add(btnSaveDraft);

        btnLoadDraft.setText("Load bản nháp");
        btnLoadDraft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadDraftActionPerformed(evt);
            }
        });
        jPanel3.add(btnLoadDraft);

        btnCancel.setText("Huỷ bỏ");
        jPanel3.add(btnCancel);

        jPanel4.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel9.setLayout(new java.awt.GridBagLayout());

        txtAreaContent.setColumns(20);
        txtAreaContent.setRows(5);
        txtAreaContent.setText("Hi,\n\nThật tuyệt vời vì được nhìn thấy rằng bạn vẫn đang ở đây cùng chúng tôi.\n\nNếu có bất kì câu hỏi nào, bạn có thể nhắn trong Discord hoặc đặt câu hỏi trực tiếp tại Workshop nhé!!\n\n>> iuhgdsc.github.io/?l=discord");
        jScrollPane1.setViewportView(txtAreaContent);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(12, 22, 12, 22);
        jPanel9.add(jScrollPane1, gridBagConstraints);

        jPanel4.add(jPanel9, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.1;
        jPanel2.add(jPanel4, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtToActionPerformed

    
    
    
    }//GEN-LAST:event_txtToActionPerformed

    private void txtFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFromActionPerformed

    
    
    }//GEN-LAST:event_txtFromActionPerformed

    private void txtSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubjectActionPerformed

    
    
    }//GEN-LAST:event_txtSubjectActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
      
      
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnLoadDraftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadDraftActionPerformed
   
    
    }//GEN-LAST:event_btnLoadDraftActionPerformed

    private void btnSaveDraftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDraftActionPerformed

    
    }//GEN-LAST:event_btnSaveDraftActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Java.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Java.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Java.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Java.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Java().setVisible(true);
            }
        });
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
    	// TODO Auto-generated method stub
    	
    	// Lấy nguồn gốc sự kiện
    	Object source = e.getSource();
    	
    	// Xử lý sự kiện trên nút tương ứng
    	if (source.equals(btnSend)) {
    		
    		if (txtFrom.getText().isBlank())
    		    JOptionPane.showMessageDialog(this, "Vui lòng nhập email người gửi!");
    		
    		else if (txtTo.getText().isBlank())
    			JOptionPane.showMessageDialog(this, "Vui lòng nhập email người nhận!");
    		else if (txtSubject.getText().isBlank())
    			JOptionPane.showMessageDialog(this, "Vui lòng nhập chủ đề!");
    		else if (txtAreaContent.getText().isBlank())
    			JOptionPane.showMessageDialog(this, "Vui lòng nhập nội dung!");

    		
		} else if (source.equals(btnCancel)) {
			txtFrom.setText("");
			txtTo.setText("");
			txtSubject.setText("");
			txtAreaContent.setText("");
		} else if (source.equals(btnSaveDraft)) {
			try {
				FileOutputStream fos = new FileOutputStream("draft.ser");
				ObjectOutputStream oos = new ObjectOutputStream(fos);
				
				Email em = new Email(0, txtFrom.getText(), txtTo.getText(), txtSubject.getText(), txtAreaContent.getText(), "");
				oos.writeObject(em);
				oos.close();
				fos.close();
				JOptionPane.showMessageDialog(this, "Lưu bản nháp thành công!");
			} catch (Exception e2) {
				e2.printStackTrace();
			}
		} else if (source.equals(btnLoadDraft)) {
			try {
				
				FileInputStream fis = new FileInputStream("draft.ser");
				ObjectInputStream ois = new ObjectInputStream(fis);
				Email em = (Email) ois.readObject();
				
				txtFrom.setText(em.getFrom());
				txtTo.setText(em.getTo());
				txtSubject.setText(em.getSubject());
				txtAreaContent.setText(em.getContent());
				ois.close();
				fis.close();
				JOptionPane.showMessageDialog(this, "Đã load bản nháp!");

			} catch (Exception e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
		}
    	
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLoadDraft;
    private javax.swing.JButton btnSaveDraft;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNewMessage;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JPanel panelNorth;
    private javax.swing.JTextArea txtAreaContent;
    private javax.swing.JTextField txtFrom;
    private javax.swing.JTextField txtSubject;
    private javax.swing.JTextField txtTo;
    // End of variables declaration//GEN-END:variables
}
