/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;

import dao.Email_DAO;
import entities.Email;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.LookAndFeel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import utilities.DBConnect;

/**
 *
 * @author duong
 */

/*
 * Để xử lý sự kiện trên nút, ta cần implement ActionListener
 */

public class JFrame_Java extends javax.swing.JFrame implements ActionListener {
	
	/*
	 * Khai báo DAO
	 * Khai báo TableModel để hiển thị dữ liệu trên bảng
	 */
	
	private Email_DAO email_DAO;
	private DefaultTableModel model;

	/**
	 * Creates new form JFrame_Java
	 */
	public JFrame_Java() {

		/*
		 * Set Look and Feel để giao diện đẹp hơn 
		 */
		
		try {
			UIManager.setLookAndFeel(new FlatMacLightLaf());
		} catch (UnsupportedLookAndFeelException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		/* 
		 *  Trước khi bắt đầu, ta sẽ connect DB trước
		 */
		
		// DBConnect..........
		
		/*
		 * Khởi tạo DAO để thao tác với Table Email
		 */
		// email_DAO ...........

		initComponents();

		setSize(700, 500);

		setTitle("Java Swing: My E-mail | Google Developer Student Clubs - IUH");

		setLocationRelativeTo(null);

		jLabel2.setPreferredSize(lblSubject.getPreferredSize());
		jLabel3.setPreferredSize(lblSubject.getPreferredSize());

		lblNewMessage.setFont(new Font("Arial", Font.BOLD, 14));


		/*
		 * Tạo table Model để hiển thị dữ liệu trên bảng
		 *  Gợi ý: 
		 *  
		 *  
		String[] header = { "ID", "From", "To", "Subject", "State" };
		model = new DefaultTableModel(header, 0);
		jTable1.setModel(model);

		 */
		
		// Thêm sự kiện cho nút
		registerEvent();
	}
	
	/*
	 * Đăng ký sự kiện cho các nút
	 */
	
	public void registerEvent() {
		btnCancel.addActionListener(this);
		btnSaveDraft.addActionListener(this);
		btnSend.addActionListener(this);
		btnRefresh.addActionListener(this);
		btnLoadEmail.addActionListener(this);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		tab1_email = new javax.swing.JTabbedPane();
		jPanel10 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		panelNorth = new javax.swing.JPanel();
		jPanel5 = new javax.swing.JPanel();
		jPanel6 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		txtFrom = new javax.swing.JTextField();
		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		txtTo = new javax.swing.JTextField();
		jPanel7 = new javax.swing.JPanel();
		lblSubject = new javax.swing.JLabel();
		txtSubject = new javax.swing.JTextField();
		jPanel8 = new javax.swing.JPanel();
		lblNewMessage = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		btnSend = new javax.swing.JButton();
		btnSaveDraft = new javax.swing.JButton();
		btnCancel = new javax.swing.JButton();
		jPanel9 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		txtAreaContent = new javax.swing.JTextArea();
		jPanel11 = new javax.swing.JPanel();
		jPanel12 = new javax.swing.JPanel();
		btnRefresh = new javax.swing.JButton();
		btnLoadEmail = new javax.swing.JToggleButton();
		jPanel13 = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel10.setLayout(new java.awt.BorderLayout());

		jPanel2.setLayout(new java.awt.GridBagLayout());

		java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
		jPanel3Layout.columnWidths = new int[] { 0, 23, 0, 23, 0 };
		jPanel3Layout.rowHeights = new int[] { 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0 };
		panelNorth.setLayout(jPanel3Layout);

		jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

		jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

		jLabel3.setText("From:");
		jPanel6.add(jLabel3);

		txtFrom.setText("core-team-members@iuhgdsc");
		txtFrom.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtFromActionPerformed(evt);
			}
		});
		jPanel6.add(txtFrom);

		jPanel5.add(jPanel6);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 0.1;
		panelNorth.add(jPanel5, gridBagConstraints);

		jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

		jLabel2.setText("To:");
		jLabel2.setPreferredSize(new java.awt.Dimension(42, 16));
		jPanel1.add(jLabel2);

		txtTo.setText("all-members@iuhgdsc");
		txtTo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtToActionPerformed(evt);
			}
		});
		jPanel1.add(txtTo);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 8;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 0.1;
		panelNorth.add(jPanel1, gridBagConstraints);

		jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

		lblSubject.setText("Subject:");
		jPanel7.add(lblSubject);

		txtSubject.setText("[IUH GDSC] Workshop Java Swing: Lời cảm ơn");
		txtSubject.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtSubjectActionPerformed(evt);
			}
		});
		jPanel7.add(txtSubject);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 12;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 0.1;
		panelNorth.add(jPanel7, gridBagConstraints);

		jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

		lblNewMessage.setText("New Message");
		jPanel8.add(lblNewMessage);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		panelNorth.add(jPanel8, gridBagConstraints);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 0.1;
		jPanel2.add(panelNorth, gridBagConstraints);

		jPanel4.setLayout(new java.awt.BorderLayout());

		btnSend.setText("Gửi");
		jPanel3.add(btnSend);

		btnSaveDraft.setText("Lưu bản nháp");
		jPanel3.add(btnSaveDraft);

		btnCancel.setText("Huỷ bỏ");
		jPanel3.add(btnCancel);

		jPanel4.add(jPanel3, java.awt.BorderLayout.PAGE_END);

		jPanel9.setLayout(new java.awt.GridBagLayout());

		txtAreaContent.setColumns(20);
		txtAreaContent.setRows(5);
		txtAreaContent.setText(
				"Hi,\n\nThật tuyệt vời vì được nhìn thấy rằng bạn vẫn đang ở đây cùng chúng tôi.\n\nNếu có bất kì câu hỏi nào, bạn có thể nhắn trong Discord hoặc đặt câu hỏi trực tiếp tại Workshop nhé!!\n\n>> iuhgdsc.github.io/?l=discord");
		jScrollPane1.setViewportView(txtAreaContent);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 0.1;
		gridBagConstraints.weighty = 0.1;
		gridBagConstraints.insets = new java.awt.Insets(12, 22, 12, 22);
		jPanel9.add(jScrollPane1, gridBagConstraints);

		jPanel4.add(jPanel9, java.awt.BorderLayout.CENTER);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.gridheight = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weighty = 0.1;
		jPanel2.add(jPanel4, gridBagConstraints);

		jPanel10.add(jPanel2, java.awt.BorderLayout.CENTER);

		tab1_email.addTab("Compose a Email", jPanel10);

		jPanel11.setLayout(new java.awt.BorderLayout());

		btnRefresh.setText("Tải lại");
		jPanel12.add(btnRefresh);

		btnLoadEmail.setText("Chỉnh sửa email");
		jPanel12.add(btnLoadEmail);

		jPanel11.add(jPanel12, java.awt.BorderLayout.PAGE_END);

		jPanel13.setLayout(new java.awt.BorderLayout());

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null }, { null, null, null, null, null },
						{ null, null, null, null, null }, { null, null, null, null, null } },
				new String[] { "ID", "From", "To", "Subject", "Body" }) {
			Class[] types = new Class[] { java.lang.Integer.class, java.lang.String.class, java.lang.Object.class,
					java.lang.String.class, java.lang.String.class };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}
		});
		jScrollPane2.setViewportView(jTable1);
		if (jTable1.getColumnModel().getColumnCount() > 0) {
			jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
		}

		jPanel13.add(jScrollPane2, java.awt.BorderLayout.CENTER);

		jPanel11.add(jPanel13, java.awt.BorderLayout.CENTER);

		tab1_email.addTab("Inbox", jPanel11);

		getContentPane().add(tab1_email, java.awt.BorderLayout.CENTER);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void txtToActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtToActionPerformed

	}// GEN-LAST:event_txtToActionPerformed

	private void txtFromActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtFromActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtFromActionPerformed

	private void txtSubjectActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtSubjectActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtSubjectActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(JFrame_Java.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(JFrame_Java.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(JFrame_Java.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(JFrame_Java.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new JFrame_Java().setVisible(true);
			}
		});
	}

	@Override
	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		Object source = e.getSource();
		
		/*
		 * Xử lý sự kiện khi click vào nút
		 */
		

	}
	

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnCancel;
	private javax.swing.JToggleButton btnLoadEmail;
	private javax.swing.JButton btnRefresh;
	private javax.swing.JButton btnSaveDraft;
	private javax.swing.JButton btnSend;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel10;
	private javax.swing.JPanel jPanel11;
	private javax.swing.JPanel jPanel12;
	private javax.swing.JPanel jPanel13;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JPanel jPanel9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTable jTable1;
	private javax.swing.JLabel lblNewMessage;
	private javax.swing.JLabel lblSubject;
	private javax.swing.JPanel panelNorth;
	private javax.swing.JTabbedPane tab1_email;
	private javax.swing.JTextArea txtAreaContent;
	private javax.swing.JTextField txtFrom;
	private javax.swing.JTextField txtSubject;
	private javax.swing.JTextField txtTo;
	// End of variables declaration//GEN-END:variables
}
